project:
  type: book

book:
  title: "Opioid Environment Toolkit for R-Spatial"
  author: "Healthy Regions & Policies Lab"
  date: "10/16/2025"
  chapters:
    - index.qmd
    - orientation.qmd
    - intro.qmd
    - geocoding.qmd
    - buffers.qmd
    - linking.qmd

bibliography: references.bib

prefer-html: true
  
format:
  html:
    self-contained: true
    embed-resources: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

comments:
  hypothesis: true
