# Census Data Wrangling

## Overview

So far, we have used spatial data to characterize access to opioid treatment resources and link those patterns with community-level information. Adding demographic, social, and economic context can help us identify whether disparities in access exist across different populations and better understand factors that may contribute to observed spatial patterns. Many of these community characteristics are available from the U.S. Census Bureau.

The American Community Survey (ACS) is an ongoing survey that provides annually updated estimates of population and housing characteristics. ACS estimates are available as 1-year and 5-year products. We generally recommend using the 5-year estimates for small geographic areas because they provide greater statistical reliability, particularly for less populated areas and smaller population subgroups. In this tutorial, we use the 2020–2024 ACS 5-year estimates, referred to as the 2024 ACS 5-year estimates.

In this tutorial, we demonstrate how to use the tidycensus package to explore and download commonly used ACS variables at multiple geographic levels, both with and without spatial geometries. We will also wrangle these data into formats that can be integrated with other spatial datasets for further analysis. This tutorial focuses on ACS data available through the Census Bureau API. Additional tutorials and documentation for tidycensus are available from the package authors.

Our objectives are thus to:

-   Download ACS data through the Census API
-   Download Census geographic boundaries
-   Explore ACS data at multiple geographic levels
-   Wrangle, clean, and merge Census data for further spatial analysis

## Environment Setup

To replicate the code and functions illustrated in this tutorial, you’ll need to have R and RStudio downloaded and installed on your system. This tutorial assumes some familiarity with the R programming language.

### Input/Output

Our only external input will be a GeoJSON file of the Chicago city boundary. This file can be found here, though all ACS data used in this tutorial will be downloaded directly from the U.S. Census Bureau using the Census API.

-   Chicago City Boundary, boundaries_chicago.geojson

We will generate Census datasets at multiple geographic levels throughout this tutorial. Our final outputs will include:

-   A CSV file and spatial file with selected ACS characteristics at the county level for the state of Illinois.
-   A CSV file and spatial file with selected ACS characteristics for zipcodes within the city of Chicago.

These outputs can be used for further spatial analysis or linked with other datasets using their geographic identifiers.

### Load Libraries

We will use the following packages in this tutorial:

-   `sf`: to manipulate spatial data
-   `tidycensus`: to download Census data using the ACS API
-   `tidyverse`: to manipulate and clean data
-   `tigris`: to download Census TIGER/Line geographic boundaries

First, load the required libraries.

```{r warning = FALSE, message=FALSE}
library(sf)
library(tidycensus)
library(tidyverse)
library(tigris)
```

## Enable Census API Key


## Load Data Dynamically


## Get Geometry


## Appendix



