project:
  type: book

book:
  title: "Health Environment R-Spatial Toolkit"
  author: "Healthy Regions & Policies Lab"
  date: "10/16/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - mapping.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

