project:
  type: book

book:
  title: "Health Environment R-Spatial Toolkit"
  author: "Healthy Regions & Policies Lab"
  date: "10/16/2025"
  chapters:
    - index.qmd
    - orientation.qmd
    - intro.qmd
    - geocoding.qmd
    - buffers.qmd
    - linking.qmd
    - references.qmd
  
 

bibliography: references.bib

prefer-html: true
  
format:
  html:
    embed-resources: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

